PROGRAM JKMAP
    IMPLICIT NONE
    CHARACTER (16), DIMENSION (:), ALLOCATABLE :: CONFIGS
    CHARACTER (64) :: ENUM_FILE, INT_FILE
    CHARACTER (5) :: BUFFER
    CHARACTER (16) :: CONFIG
    INTEGER, DIMENSION (:), ALLOCATABLE :: IDS, POSA, POSB, DIST
    INTEGER :: N, M, NUMLINES = 0, HEADER = 0, STEPS = 201, SA, SB, J, K
    INTEGER, DIMENSION(4, 4, 2) :: INTMATRIX = 0
    REAL, DIMENSION (:), ALLOCATABLE :: INTVALS

    CALL GETARG(1, ENUM_FILE)
    CALL GETARG(2, INT_FILE)
    OPEN(1, FILE=ENUM_FILE)
!   COUNT LINES IN ENUM FILE
    DO
        READ(1, *, END=1001)
        NUMLINES = NUMLINES + 1
    END DO
    1001 CLOSE(1)
    OPEN(1, FILE=ENUM_FILE)
!   READ SKIP THE HEADER INFO IN ENUM FILE
    DO WHILE(BUFFER /= 'start')
        READ(1, *) BUFFER
        HEADER = HEADER + 1
    END DO
    ALLOCATE(CONFIGS(NUMLINES - HEADER))
    ALLOCATE(IDS(NUMLINES - HEADER))
!   READ CONFIGURATIONS FROM ENUM FILE
    DO N = 1, NUMLINES - HEADER
        READ(1, *) IDS(N), BUFFER, BUFFER, BUFFER, BUFFER, &
            BUFFER, BUFFER, BUFFER, BUFFER, BUFFER, &
            BUFFER, BUFFER, BUFFER, BUFFER, BUFFER, &
            BUFFER, BUFFER, BUFFER, BUFFER, BUFFER, &
            BUFFER, BUFFER, BUFFER, BUFFER, BUFFER, &
            BUFFER, CONFIGS(N)
    END DO
    CLOSE(1)
    OPEN(1, FILE=INT_FILE)
    NUMLINES = 0
!   GET LENGTH OF INTERACTION FILE
    DO
        READ(1, *, END=1002)
        NUMLINES = NUMLINES + 1
    END DO
    1002 CLOSE(1)
    ALLOCATE(POSA(NUMLINES))
    ALLOCATE(POSB(NUMLINES))
    ALLOCATE(DIST(NUMLINES))
    OPEN(1, FILE=INT_FILE)
!   READ INTERACTION FILE
    DO N = 1, NUMLINES
        READ(1, *)  POSA(N), POSB(N), DIST(N)
    END DO
    CLOSE(1)
    ALLOCATE(INTVALS(STEPS))
!   SET INTMATRIX TO COUNT J/K INTERACTIONS
!   ALL VALUES IN THIS MATRIX SHOULD BE
!   ONE OR ZERO BECAUSE THIS IS A TALLY
    INTMATRIX(1, 1, 1) = 1
    !INTMATRIX(1, 2, 1) = 1
    !INTMATRIX(2, 1, 1) = 1
    INTMATRIX(2, 2, 1) = 1
    INTMATRIX(3, 3, 1) = 1
    !INTMATRIX(3, 4, 1) = 1
    !INTMATRIX(4, 3, 1) = 1
    INTMATRIX(4, 4, 1) = 1
    INTMATRIX(1, 1, 2) = 1 
    INTMATRIX(2, 2, 2) = 1 
    INTMATRIX(3, 3, 2) = 1 
    INTMATRIX(4, 4, 2) = 1
    DO N = 1, SIZE(CONFIGS)
        CONFIG = CONFIGS(N)
        J = 0
        K = 0
        DO M = 1, SIZE(POSA)
            READ(CONFIG(POSA(M):POSA(M)), *) SA
            READ(CONFIG(POSB(M):POSB(M)), *) SB
!           COUNT ALL J/K-TYPE INTERACTIONS
            IF (DIST(M) == 1) THEN
                J = J + INTMATRIX(SA + 1, SB + 1, 1)
            ELSEIF (DIST(M) == 2) THEN
                K = K + INTMATRIX(SA + 1, SB + 1, 2)
            ENDIF
        END DO
        WRITE(*, FMT="(I3, A1, I3, A2, A16)") J, "," , K, ",", CONFIG
    END DO
    DEALLOCATE(INTVALS)
    DEALLOCATE(CONFIGS)
    DEALLOCATE(IDS)
END PROGRAM

SUBROUTINE LINSPACE(Z, L, K, N)
!###################################
! FILLS THE ARRAY Z WITH N NUMBERS #
! EVENLY SPACED BETWEEN L AND K    #
! (INCLUSIVELY)                    #
!###################################
    IMPLICIT NONE
    INTEGER :: N, I
    REAL, DIMENSION(N) :: Z
    REAL :: D, L, K
    D = (K - L) / N
    Z(1) = L
    DO I = 2, N - 1
        Z(I) = Z(I-1) + D
    END DO
    Z(1) = L
    Z(N) = K
    RETURN
END SUBROUTINE
